# .github/workflows/ci-cd.yml

name: CI/CD Pipeline for Chirion (Vite React App)

on:
  push:
    branches:
      - Dev
      - Add-CICD
  pull_request:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Navigate to the web directory
      - name: Change to web directory
        run: cd web

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        
        with:
          node-version: '18'
          cache: 'npm'
      
      # Install dependencies
      - name: Install dependencies
        run: npm install
      
      # Run tests
      - name: Run tests
        run: npm test
        
      # Build the application
      - name: Build application
        run: npm run build
        

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
        